// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rolgjcpalybdovfbmyxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvbGdqY3BhbHliZG92ZmJteXhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0OTgxNzcsImV4cCI6MjA5MTA3NDE3N30.wjwBWcYQeghv_SfU1RTRIiJl3pXcBRrbas83bVyyBj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});